# -*- coding: utf-8 -*-
"""Feature Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jsG9TRHbclkKXeoYPaMO3pqzhaX8kk-k
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#to display plots inline
# %matplotlib inline

from google.colab import drive

# Mount Google Drive
drive.mount('/content/gdrive')

# Load the cleaned dataset
cleaned_data_path = '/content/gdrive/My Drive/Colab Notebooks/Sales Trends Analysis Project/cleaned_dataset.csv'
df_cleaned = pd.read_csv(cleaned_data_path)

# Display the first few rows to verify
df_cleaned.head()

# Check the shape of the dataset
print(df_cleaned.shape)

# Check for any remaining missing values
print(df_cleaned.isnull().sum())

# Display data types to confirm they are correct
print(df_cleaned.dtypes)

"""# Feature Engineering

**Creating New Time-Based Features**
"""

# Convert Invoice_date to datetime
df_cleaned['Invoice_date'] = pd.to_datetime(df_cleaned['Invoice_date'], errors='coerce')

# Verify the conversion
print(df_cleaned['Invoice_date'].head())

# Drop rows where Invoice_date could not be converted
df_cleaned.dropna(subset=['Invoice_date'], inplace=True)

df_cleaned['Year'] = df_cleaned['Invoice_date'].dt.year

df_cleaned['Month'] = df_cleaned['Invoice_date'].dt.month

df_cleaned['Day'] = df_cleaned['Invoice_date'].dt.day

df_cleaned['DayOfWeek'] = df_cleaned['Invoice_date'].dt.dayofweek

df_cleaned['Hour'] = df_cleaned['Invoice_date'].dt.hour

df_cleaned.head()

# Create Weekday feature
df_cleaned['Weekday'] = df_cleaned['Invoice_date'].dt.day_name()

df_cleaned.head()

# Create Quarter feature
df_cleaned['Quarter'] = df_cleaned['Invoice_date'].dt.quarter

df_cleaned.head()

# Create Total Sales feature
df_cleaned['Total_Sales'] = df_cleaned['Quantity'] * df_cleaned['Price']

df_cleaned.head()

feature_engineered_data_path = '/content/gdrive/My Drive/Colab Notebooks/Sales Trends Analysis Project/feature_engineered_dataset.csv'
df_cleaned.to_csv(feature_engineered_data_path, index=False)